[Theme]
Current=mint-arch

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot
Numlock=on

[Autologin]
Relogin=false

[X11]
ServerPath=/usr/bin/X
ServerArguments=-nolisten tcp -dpi 96

[Wayland]
CompositorCommand=kwin_wayland --drm --no-lockscreen
